import FolderTree from "@/components/FolderTree";
import { ChevronRight } from "lucide-react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";

const folders = [
  {
    path: "app/",
    purpose: "Main routing directory using Next.js App Router. Each sub-folder becomes a URL route.",
    files: ["layout.tsx", "page.tsx", "globals.css"],
  },
  {
    path: "components/",
    purpose: "All reusable React UI components grouped by feature domain.",
    files: ["global-provider/", "profile/", "settings/", "sidebar/", "ui/"],
  },
  {
    path: "components/ui/",
    purpose: "Shared atomic UI primitives with no business logic — used across all features.",
    files: ["empty-state.tsx", "error-state.tsx", "header.tsx", "loading-state.tsx", "logo.tsx"],
  },
  {
    path: "helpers/",
    purpose: "Non-UI utility functions and guard components that support application logic.",
    files: ["domain-finder.ts", "role-gateway.tsx"],
  },
  {
    path: "hooks/",
    purpose: "Custom React hooks shared across the application (data fetching, auth state, etc.).",
    files: ["useUser.ts", "useSettings.ts"],
  },
  {
    path: "lib/",
    purpose: "Core library utilities and shared helper functions used project-wide.",
    files: ["utils.ts"],
  },
  {
    path: "store/",
    purpose: "Global client-side state management using Zustand, split by user role.",
    files: ["superadmin/", "user/"],
  },
  {
    path: "store/superadmin/",
    purpose: "Zustand stores scoped to superadmin — app-wide settings, admin-only state.",
    files: ["app-settings-store.ts", "general-store.ts"],
  },
  {
    path: "store/user/",
    purpose: "Zustand stores scoped to regular users — user preferences and session state.",
    files: ["app-settings-store.ts", "general-store.ts"],
  },
  {
    path: "supabase/",
    purpose: "Supabase SQL schema migration files — defines database tables, RLS policies, and indexes.",
    files: ["settings_schema.sql", "chatbot_schema.sql", "endpoint_schema.sql"],
  },
  {
    path: "type/",
    purpose: "Shared TypeScript type definitions used across the entire codebase.",
    files: ["database-type.ts", "general-type.ts"],
  },
  {
    path: "utils/",
    purpose: "Runtime utility modules split by external service.",
    files: ["supabase/"],
  },
  {
    path: "utils/supabase/",
    purpose: "Supabase client factory functions — returns the correct client based on execution context (browser, server, or proxy).",
    files: ["admin.ts", "client.ts", "index.ts", "proxy.ts", "server.ts"],
  },
  {
    path: "public/",
    purpose: "Static assets served directly at the root URL — images, icons, and fonts.",
    files: ["favicon.ico", "logo.png"],
  },
  {
    path: "node_modules/",
    purpose: "Auto-generated by npm. Contains all installed third-party packages. Never edit manually.",
    files: ["(managed by npm)"],
  },
  {
    path: ".next/",
    purpose: "Auto-generated Next.js build output. Created on next build or next dev. Never edit manually.",
    files: ["(managed by Next.js)"],
  },
];

export default function LayoutSection() {
  return (
    <section id="layout" className="mt-16 scroll-mt-20 border-t pt-16">
      <div className="mb-4 flex items-center space-x-1 text-sm text-muted-foreground">
        <div>Development Guide</div>
        <ChevronRight className="h-4 w-4" />
        <div className="font-medium text-foreground">Layout</div>
      </div>
      <h2 className="scroll-m-20 pb-2 text-3xl font-semibold tracking-tight">
        Layout &amp; Project Structure
      </h2>
      <p className="mt-4 leading-7">
        Visual representation of our project architecture and folder
        organization. Click folders in the tree to expand or collapse them.
      </p>
      <div id="project-structure" className="scroll-mt-20">
        <FolderTree />
      </div>

      <div className="mt-8 overflow-hidden rounded-lg border">
        <Table>
          <TableHeader className="bg-muted/50">
            <TableRow>
              <TableHead className="w-[200px]">Folder</TableHead>
              <TableHead>Purpose</TableHead>
              <TableHead className="w-[260px]">Files inside</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {folders.map(({ path, purpose, files }) => (
              <TableRow key={path} className="hover:bg-muted/30 transition-colors align-top">
                <TableCell className="font-mono text-xs whitespace-nowrap text-primary align-top">
                  {path}
                </TableCell>
                <TableCell className="text-muted-foreground">{purpose}</TableCell>
                <TableCell className="align-top">
                  <div className="flex flex-wrap gap-1">
                    {files.map((f) => (
                      <Badge
                        key={f}
                        variant="secondary"
                        className="rounded px-1.5 py-0.5 font-mono text-[11px] text-muted-foreground bg-muted border-none"
                      >
                        {f}
                      </Badge>
                    ))}
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </section>
  );
}
